import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  BookOpen,
  Bot,
  Box,
  Braces,
  Brain,
  Cloud,
  CreditCard,
  Database,
  Flame,
  GitBranch,
  Globe,
  Layers,
  Link2,
  Mail,
  MousePointer2,
  Paintbrush,
  PieChart,
  RefreshCw,
  Search,
  Server,
  Sparkles,
  Table2,
  Triangle,
  Zap,
} from "lucide-react";

/** Per-tool icons for the tech stack grid & marquee */
export const TECH_TOOL_ICONS: Record<string, LucideIcon> = {
  "Next.js 16": Layers,
  "React 19": Sparkles,
  TypeScript: Braces,
  "Tailwind CSS v4": Paintbrush,
  "HTML5 & CSS3": Globe,
  "Shadcn UI / Radix": Layers,
  "Zustand / Redux": Box,
  "Framer Motion": Sparkles,
  Python: Braces,
  FastAPI: Zap,
  "Django / Flask": Braces,
  "Node.js": Box,
  "Express.js": Server,
  "PHP / Laravel": Flame,
  GraphQL: GitBranch,
  "REST APIs & Webhooks": Globe,
  WebSockets: Zap,
  PostgreSQL: Database,
  MySQL: Database,
  MongoDB: Database,
  "Vector Databases": Search,
  Redis: Database,
  PyTorch: Flame,
  TensorFlow: BarChart3,
  "Scikit-learn": BarChart3,
  "Pandas / NumPy": Table2,
  "Prisma / Mongoose": Link2,
  LangChain: Link2,
  LlamaIndex: Link2,
  "RAG pipelines": BookOpen,
  "Ollama / Gemma 4": Bot,
  "OpenAI GPT-4o": Brain,
  "Claude 3.5 Sonnet": Brain,
  "Hugging Face": Brain,
  Playwright: MousePointer2,
  "Google Cloud": Cloud,
  AWS: Cloud,
  "Microsoft Azure": Cloud,
  Docker: Box,
  Kubernetes: Layers,
  "Supabase / Firebase": Database,
  Vercel: Triangle,
  "GitHub Actions": RefreshCw,
  Stripe: CreditCard,
  "Shopify / WooCommerce": CreditCard,
  "MCP Protocol": Link2,
  "Monday.com API": BarChart3,
  Streamlit: BarChart3,
  "Zapier / Make.com": Link2,
  Resend: Mail,
};

export function getTechToolIcon(name: string): LucideIcon {
  return TECH_TOOL_ICONS[name] ?? Box;
}
