import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  BookOpen,
  Bot,
  Box,
  Braces,
  Brain,
  Cloud,
  CreditCard,
  Database,
  Flame,
  GitBranch,
  Globe,
  Layers,
  Link2,
  MousePointer2,
  Paintbrush,
  PieChart,
  RefreshCw,
  Search,
  Server,
  Sparkles,
  Table2,
  Triangle,
  Zap,
} from "lucide-react";

/** Per-tool icons for the tech stack grid & marquee */
export const TECH_TOOL_ICONS: Record<string, LucideIcon> = {
  "Next.js 16": Layers,
  "React 19": Sparkles,
  TypeScript: Braces,
  "Tailwind CSS v4": Paintbrush,
  "Framer Motion": Sparkles,
  Python: Braces,
  FastAPI: Zap,
  Flask: Server,
  "Node.js": Box,
  GraphQL: GitBranch,
  "REST APIs & Webhooks": Globe,
  PHP: Server,
  Laravel: Flame,
  PostgreSQL: Database,
  MySQL: Database,
  MongoDB: Database,
  "Vector Databases": Search,
  "Scikit-learn": BarChart3,
  "Pandas / NumPy": Table2,
  LangChain: Link2,
  "RAG pipelines": BookOpen,
  "Ollama / Gemma 4": Bot,
  "OpenAI GPT-4o": Brain,
  Playwright: MousePointer2,
  "Google Cloud": Cloud,
  AWS: Cloud,
  "Microsoft Azure": Cloud,
  Docker: Box,
  Firebase: Flame,
  Vercel: Triangle,
  "CI/CD": RefreshCw,
  Stripe: CreditCard,
  "MCP Protocol": Link2,
  "Monday.com API": BarChart3,
  Streamlit: BarChart3,
  "Power BI export": PieChart,
  "HTML5 & CSS3": Globe,
};

export function getTechToolIcon(name: string): LucideIcon {
  return TECH_TOOL_ICONS[name] ?? Box;
}
